name: Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    environment: Main

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Поиск файла .xcodeproj
      - name: Find .xcodeproj File
        id: find_project
        run: |
          echo "Looking for .xcodeproj file in repository root..."
          PROJECT_FILE=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "❌ No .xcodeproj file found in the repository root!"
            exit 1
          fi
          PROJECT_NAME=$(basename "$PROJECT_FILE" .xcodeproj)
          echo "✅ Found .xcodeproj file: $PROJECT_FILE"
          echo "✅ Project Name: $PROJECT_NAME"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROJECT_FILE=$PROJECT_FILE" >> $GITHUB_ENV

      # Шаг 3: Установка сертификата (.p12)
      - name: Set up Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_FILE }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      # Шаг 4: Установка профиля профилирования
      - name: Install Provisioning Profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ./YourProfile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./YourProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Шаг 5: Сборка приложения
      - name: Build iOS app
        run: |
          xcodebuild clean archive \
            -project "${PROJECT_FILE}" \
            -scheme "${PROJECT_NAME}" \
            -archivePath "${{ github.workspace }}/build/${PROJECT_NAME}.xcarchive" \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            -allowProvisioningUpdates

      # Шаг 6: Экспорт архива в .ipa
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "${{ github.workspace }}/build/${PROJECT_NAME}.xcarchive" \
            -exportPath "${{ github.workspace }}/build" \
            -exportOptionsPlist ExportOptions.plist \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            -allowProvisioningUpdates

      # Шаг 7: Загрузка .ipa в TestFlight через API Key
      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            -f "${{ github.workspace }}/build/${PROJECT_NAME}.ipa" \
            -t ios \
            --apiKey "${{ secrets.API_KEY_ID }}" \
            --apiIssuer "${{ secrets.API_ISSUER_ID }}"

      # Шаг 8: Очистка билдов
      - name: Clean up build files
        run: rm -rf "${{ github.workspace }}/build