name: Deploy to TestFlight

on:
  push:
    branches:
      - main  # Ветка для деплоя

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка сертификата (.p12)
      - name: Set up Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.P12_FILE }}  # Сертификат в Base64
          p12-password: ${{ secrets.P12_PASSWORD }} # Пароль для сертификата

      # Шаг 3: Установка профиля профилирования
      - name: Install Provisioning Profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ./YourProfile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./YourProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Шаг 4: Сборка приложения
      - name: Build iOS app
        run: |
          xcodebuild clean archive \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -archivePath ${{ github.workspace }}/build/YourApp.xcarchive \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            -allowProvisioningUpdates

      # Шаг 5: Экспорт архива в .ipa
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/YourApp.xcarchive \
            -exportPath ${{ github.workspace }}/build \
            -exportOptionsPlist ExportOptions.plist \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            -allowProvisioningUpdates

      # Шаг 6: Загрузка .ipa в TestFlight через API Key
      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            -f ${{ github.workspace }}/build/YourApp.ipa \
            -t ios \
            --apiKey ${{ secrets.API_KEY_ID }} \
            --apiIssuer ${{ secrets.API_ISSUER_ID }}

      # Шаг 7: Очистка билдов
      - name: Clean up build files
        run: rm -rf ${{ github.workspace }}/build