name: Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest
    environment: Main

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка профиля профилирования
      - name: Install Provisioning Profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ./YourProfile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ./YourProfile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Шаг 3: Создание AuthKey.p8 из секрета
      - name: Create AuthKey.p8 from secret
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_KEY }}" > ./AuthKey.p8

      # Шаг 4: Поиск имени проекта
      - name: Find .xcodeproj File
        id: find_project
        run: |
          echo "Looking for .xcodeproj file in repository root..."
          PROJECT_FILE=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "❌ No .xcodeproj file found in the repository root!"
            exit 1
          fi
          PROJECT_NAME=$(basename "$PROJECT_FILE" .xcodeproj)
          echo "✅ Found .xcodeproj file: $PROJECT_FILE"
          echo "✅ Project Name: $PROJECT_NAME"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROJECT_FILE=$PROJECT_FILE" >> $GITHUB_ENV

      # Шаг 5: Сборка приложения
      - name: Build iOS app
        run: |
          AUTH_KEY_PATH="$(pwd)/AuthKey.p8"
          xcodebuild clean archive \
            -project "${PROJECT_FILE}" \
            -scheme "${PROJECT_NAME}" \
            -archivePath "${{ github.workspace }}/build/${PROJECT_NAME}.xcarchive" \
            -authenticationKeyID "${{ secrets.API_KEY_ID }}" \
            -authenticationKeyIssuerID "${{ secrets.API_ISSUER_ID }}" \
            -authenticationKeyPath "${AUTH_KEY_PATH}" \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            -allowProvisioningUpdates

      # Шаг 6: Экспорт архива в .ipa
      - name: Export IPA
        run: |
          AUTH_KEY_PATH="$(pwd)/AuthKey.p8"
          xcodebuild -exportArchive \
            -archivePath "${{ github.workspace }}/build/${PROJECT_NAME}.xcarchive" \
            -exportPath "${{ github.workspace }}/build" \
            -exportOptionsPlist ExportOptions.plist \
            -authenticationKeyID "${{ secrets.API_KEY_ID }}" \
            -authenticationKeyIssuerID "${{ secrets.API_ISSUER_ID }}" \
            -authenticationKeyPath "${AUTH_KEY_PATH}" \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM_ID }}" \
            -allowProvisioningUpdates

      # Шаг 7: Загрузка .ipa в TestFlight
      - name: Upload to TestFlight
        run: |
          AUTH_KEY_PATH="$(pwd)/AuthKey.p8"
          xcrun altool --upload-app \
            -f "${{ github.workspace }}/build/${PROJECT_NAME}.ipa" \
            -t ios \
            --apiKey "${{ secrets.API_KEY_ID }}" \
            --apiIssuer "${{ secrets.API_ISSUER_ID }}"

      # Шаг 8: Очистка временных файлов
      - name: Clean up temporary files
        run: |
          rm -f ./AuthKey.p8
          rm -f ./YourProfile.mobileprovision